//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoShop.Models.EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoDeo_Magacin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutoDeo_Magacin()
        {
            this.StavkaRacuna = new HashSet<StavkaRacuna>();
            this.UnosMagacin = new HashSet<UnosMagacin>();
        }
    
        public int IDMagacin { get; set; }
        public int IDAutoDeo { get; set; }
        public int Stanje { get; set; }
    
        public virtual AutoDeo AutoDeo { get; set; }
        public virtual Magacin Magacin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaRacuna> StavkaRacuna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnosMagacin> UnosMagacin { get; set; }
    }
}
