//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoShop.Models.EntityDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoShopEntities : DbContext
    {
        public AutoShopEntities()
            : base("name=AutoShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutoDeo> AutoDeo { get; set; }
        public virtual DbSet<AutoDeo_Magacin> AutoDeo_Magacin { get; set; }
        public virtual DbSet<Magacin> Magacin { get; set; }
        public virtual DbSet<Racun> Racun { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Role_User> Role_User { get; set; }
        public virtual DbSet<StavkaRacuna> StavkaRacuna { get; set; }
        public virtual DbSet<UnosMagacin> UnosMagacin { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
