//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoShop.Models.EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaRacuna
    {
        public int IDRacuna { get; set; }
        public int IDStavkaRacuna { get; set; }
        public int IDMagacin { get; set; }
        public int IDAutoDeo { get; set; }
        public int Kolicina { get; set; }
        public double JedCena { get; set; }
        public double Vrednost { get; set; }
    
        public virtual AutoDeo_Magacin AutoDeo_Magacin { get; set; }
        public virtual Racun Racun { get; set; }
    }
}
