//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoShop.Models.EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnosMagacin
    {
        public int ID { get; set; }
        public int IDMagacin { get; set; }
        public int IDAutoDeo { get; set; }
        public int Kolicina { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<System.TimeSpan> Vreme { get; set; }
    
        public virtual AutoDeo_Magacin AutoDeo_Magacin { get; set; }
    }
}
